java_binary(
    name = "turnstile",
    main_class = "com.hounshell.st8.demos.turnstile.TurnstileDemo",
    javacopts = ["--enable-preview"],
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/hounshell/st8",
    ],
)
